from __future__ import annotations

from pathlib import Path

from betteruv.core.models import ResolvePlan


def write_requirements_file(repo_root: Path, plan: ResolvePlan) -> Path:
    output_path = repo_root / "requirements.inferred.txt"
    lines = [
        "# Generated by betteruv",
        "# Review before committing for production use.",
        "",
    ]
    lines.extend(sorted(set(plan.packages)))
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path